### ISSUE TITLE
qemu-img resize timeout

### ISSUE THREAD

**Issue by uplight-dev** [kpma1985/ansible_proxmox_hetzner#10]
Sometimes the resize of the OPNsense volume fails with timeout after 25 seconds of waiting:
`/usr/bin/qemu-img resize -f raw /var/lib/vz/images/9000/vm-9000-disk-0.raw 10737418240'' failed: got timeout`

However after this, tried to run only this specific ansible task again and the resize call succeeds.
And some other times the full installation works.
Duplicating this task in the playbook with ignoreErrors: true, and the call succeeds usually on the 2nd attempt.

Options:
  - [Found](https://github.com/canonical/multipass/pull/2937) that in a later(March 2023) qemu-img version, the timeout was increased to 5 minutes but the existing proxmox installation doesn't allow to update apt
  - [Another post](https://github.com/canonical/multipass/issues/1408) recommends to create bigger volume + copy existing data; this looks like a workaround to me

Any ideas? Thanks!

**Comment by kpma1985** [comment]
Whats the HW specs? If it is not a ssd or nvme. You can try to speed down the raid rebuild.
Otherwise try with qemu convert 
Thank you

**Comment by uplight-dev** [comment]
It's an AX41 with 2x 5TB HDD, not a ssd/nvme.
Thanks, I'll try!
