### ISSUE TITLE
problems launching playbook

### ISSUE THREAD

**Issue by agapitox** [kpma1985/ansible_proxmox_hetzner#3]
Hello,

I have been trying to run the playbook but I am not able to.

I have put the variables in the host file, but when I launch the pb, I get this:

```
dvillalobos@M910X:~/ansible_proxmox_hetzner$ ansible-playbook -i inventory/hosts playbook.yml

PLAY [Install PROXMOX] *************************************************************************************************

TASK [Check for SSH Port] **********************************************************************************************
fatal: [estorjeador.atroz.network]: FAILED! => {"changed": false, "elapsed": 10, "msg": "Timeout when waiting for estorjeador.atroz.network:48622"}
...ignoring

TASK [set ansible_port] ************************************************************************************************
skipping: [estorjeador.atroz.network]

TASK [ansible.builtin.setup] *******************************************************************************************
fatal: [estorjeador.atroz.network]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'estorjeador.atroz.network' (ED25519) to the list of known hosts.\r\nroot@estorjeador.atroz.network: Permission denied (publickey,password).", "unreachable": true}

PLAY RECAP *************************************************************************************************************
estorjeador.atroz.network  : ok=1    changed=0    unreachable=1    failed=0    skipped=1    rescued=0    ignored=1

dvillalobos@M910X:~/ansible_proxmox_hetzner$

```

but if I launch an ssh against the host it comes in without any problems...

I don't know what I'm doing wrong. can you help me?

I don't know how to work with secrets and ansible either, I don't know if that has something to do with it too.

Thank you very much for your help.

**Comment by kpma1985** [comment]
Hello,
last time i checked, hetzner changed the filename for the rescueimage. maybe there are more changes.

**Comment by agapitox** [comment]
Do you need any logs from me?

**Comment by agapitox** [comment]
hello are you going to be able to check the error or am I forgetting the issue?

thank you very much

**Comment by umekzg** [comment]
Any update on this?

Script is awesome but it doesn't work

**Comment by agapitox** [comment]
it's a pity... because it looks very good, but it seems that @kpma1985  doesn't care and has no interest in checking it.

**Comment by agapitox** [comment]
> Hello,
> last time i checked, hetzner changed the filename for the rescueimage. maybe there are more changes.

Where can I review these changes? What files are they in?

**Comment by kpma1985** [comment]
Try it now.

**Comment by agapitox** [comment]
> Try it now.

Thank you very much for your answer

now it runs fine but after the first reboot it won't start up

my server is a SX133

![image](https://user-images.githubusercontent.com/9149573/218308058-b9102a6e-fca2-4af0-a93e-ce3a22c7e189.gif)

**Comment by kpma1985** [comment]
please try to restart manually into the rescue mode and run the playbook

<img width="862" alt="Bildschirm­foto 2023-02-12 um 12 33 30" src="https://user-images.githubusercontent.com/4441318/218308513-b169fc96-8865-4062-9fc0-71ef17e35852.png">

**Comment by agapitox** [comment]
Yes, I've always thrown it that way.

I activate rescue mode, reboot and launch the playbook.

**Comment by kpma1985** [comment]
i did a quickfix - try now. just installed on a ax51

**Comment by agapitox** [comment]
> i did a quickfix - try now. just installed on a ax51

Now, it stays here and does not move forward. I'm putting something wrong?

thank you for your patience
![image](https://user-images.githubusercontent.com/9149573/218331027-085c4484-fe18-4c74-b064-1580cb2a95eb.gif)

**Comment by agapitox** [comment]
> i did a quickfix - try now. just installed on a ax51

tell me how did you launch it? what variables did you put in?

thanks

**Comment by agapitox** [comment]
hi,

I have solved this

<img width="484" alt="image" src="https://user-images.githubusercontent.com/9149573/220710521-c133cfeb-d47f-4839-823e-19027e7c5f02.png">

had some secureboot active on the board

**Comment by agapitox** [comment]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/9149573/220733637-fed78fde-9238-4df3-bff3-85c56dc811be.png">

now gets stuck at this point: fixed!!

**Comment by agapitox** [comment]
I've made some progress, but now it's stuck at this point.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/9149573/220785852-1dbfe1d1-f12c-4013-847c-bd3c683b8fe4.png">


I have already seen how to deactivate it... and the installation continues.

**Comment by agapitox** [comment]
now fails to create the opnesense interface:



`
TASK [hetzner_pve : OPNsense Preapare - Update LAN Interface (2/2)] ****************************************************************
task path: /home/dvillalobos/ansible_proxmox_hetzner/roles/hetzner_pve/tasks/09_opnsense_prepare.yml:86
<estorjeador.atroz.network> ESTABLISH SSH CONNECTION FOR USER: root
<estorjeador.atroz.network> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/dvillalobos/.ssh/id_ed25519_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/dvillalobos/.ansible/cp/b327b16e1b estorjeador.atroz.network '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<estorjeador.atroz.network> (0, b'/root\n', b'')
<estorjeador.atroz.network> ESTABLISH SSH CONNECTION FOR USER: root
<estorjeador.atroz.network> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/dvillalobos/.ssh/id_ed25519_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/dvillalobos/.ansible/cp/b327b16e1b estorjeador.atroz.network '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347 `" && echo ansible-tmp-1677321766.4628022-14160-195190787184347="` echo /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347 `" ) && sleep 0'"'"''
<estorjeador.atroz.network> (0, b'ansible-tmp-1677321766.4628022-14160-195190787184347=/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347\n', b'')
Using module file /usr/lib/python3/dist-packages/ansible_collections/community/general/plugins/modules/xml.py
<estorjeador.atroz.network> PUT /home/dvillalobos/.ansible/tmp/ansible-local-13244jo34lfml/tmpdltkdf_t TO /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py
<estorjeador.atroz.network> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/dvillalobos/.ssh/id_ed25519_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/dvillalobos/.ansible/cp/b327b16e1b '[estorjeador.atroz.network]'
<estorjeador.atroz.network> (0, b'sftp> put /home/dvillalobos/.ansible/tmp/ansible-local-13244jo34lfml/tmpdltkdf_t /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py\n', b'')
<estorjeador.atroz.network> ESTABLISH SSH CONNECTION FOR USER: root
<estorjeador.atroz.network> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/dvillalobos/.ssh/id_ed25519_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/dvillalobos/.ansible/cp/b327b16e1b estorjeador.atroz.network '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/ /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py && sleep 0'"'"''
<estorjeador.atroz.network> (0, b'', b'')
<estorjeador.atroz.network> ESTABLISH SSH CONNECTION FOR USER: root
<estorjeador.atroz.network> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/dvillalobos/.ssh/id_ed25519_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/dvillalobos/.ansible/cp/b327b16e1b -tt estorjeador.atroz.network '/bin/sh -c '"'"'/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py && sleep 0'"'"''
<estorjeador.atroz.network> (1, b'Traceback (most recent call last):\r\n  File "/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py", line 40, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.community.general.plugins.modules.xml\', init_globals=None, run_name=\'__main__\', alter_sys=True)\r\n  File "/usr/lib/python3.9/runpy.py", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 958, in <module>\r\n  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 944, in main\r\n  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 662, in set_target\r\n  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 648, in set_target_inner\r\n  File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__\r\n  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText\r\n  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode\r\n  File "src/lxml/apihelpers.pxi", line 1539, in lxml.etree._utf8\r\nTypeError: Argument must be bytes or unicode, got \'int\'\r\n', b'Shared connection to estorjeador.atroz.network closed.\r\n')
<estorjeador.atroz.network> Failed to connect to the host via ssh: Shared connection to estorjeador.atroz.network closed.
<estorjeador.atroz.network> ESTABLISH SSH CONNECTION FOR USER: root
<estorjeador.atroz.network> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/dvillalobos/.ssh/id_ed25519_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/dvillalobos/.ansible/cp/b327b16e1b estorjeador.atroz.network '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/ > /dev/null 2>&1 && sleep 0'"'"''
<estorjeador.atroz.network> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.xml', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 958, in <module>
  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 944, in main
  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 662, in set_target
  File "/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py", line 648, in set_target_inner
  File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1539, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'int'
fatal: [estorjeador.atroz.network]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to estorjeador.atroz.network closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1677321766.4628022-14160-195190787184347/AnsiballZ_xml.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.xml', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 958, in <module>\r\n  File \"/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 944, in main\r\n  File \"/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 662, in set_target\r\n  File \"/tmp/ansible_community.general.xml_payload_oqkr9aer/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 648, in set_target_inner\r\n  File \"src/lxml/etree.pyx\", line 1042, in lxml.etree._Element.text.__set__\r\n  File \"src/lxml/apihelpers.pxi\", line 748, in lxml.etree._setNodeText\r\n  File \"src/lxml/apihelpers.pxi\", line 736, in lxml.etree._createTextNode\r\n  File \"src/lxml/apihelpers.pxi\", line 1539, in lxml.etree._utf8\r\nTypeError: Argument must be bytes or unicode, got 'int'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************************************
estorjeador.atroz.network  : ok=67   changed=36   unreachable=0    failed=1    skipped=8    rescued=0    ignored=2

dvillalobos@M910X:~/ansible_proxmox_hetzner$`

**Comment by agapitox** [comment]
I give up... it doesn't work... it fails everywhere.

**Comment by kpma1985** [comment]
> I've made some progress, but now it's stuck at this point.
> 
> <img alt="image" width="936" src="https://user-images.githubusercontent.com/9149573/220785852-1dbfe1d1-f12c-4013-847c-bd3c683b8fe4.png">
> 
> I have already seen how to deactivate it... and the installation continues.

did you add the credentials and activate samba?


```
### Setup StorageBox as Mount
hetzner_pve_storagebox_setup: true
hetzner_pve_storagebox_server:
  - name: xxxxx.your-storagebox.de
    user: xxxxx
    pass: xxxxx
```
